ip: "192.168.137.1"

runner:
  i7:
    hw:
      cpu: 26.0
      memory: "10G"
    workers: 
      high: 10
      normal: 8
      mid: 6
      low: 4
  i5:
    hw:
      cpu: 18.0
      memory: "5G"
    workers: 
      high: 6
      normal: 4
      mid: 3
      low: 2
